- name: packagecloud dokku apt key
  apt_key:
    url: https://packagecloud.io/dokku/dokku/gpgkey
  tags:
  - dokku

- name: dokku repo
  apt_repository:
    filename: dokku
    repo: 'deb https://packagecloud.io/dokku/dokku/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main'  # yamllint disable-line rule:line-length

    state: present
  tags:
  - dokku

- name: debconf dokku/hostname
  debconf:
    name: dokku
    question: 'dokku/hostname'
    value: '{{ dokku_hostname }}'
    vtype: 'string'
  tags:
  - dokku

- name: debconf dokku/key_file
  debconf:
    name: dokku
    question: 'dokku/key_file'
    value: '{{ dokku_key_file }}'
    vtype: 'string'
  tags:
  - dokku

- name: debconf dokku/skip_key_file
  debconf:
    name: dokku
    question: 'dokku/skip_key_file'
    value: '{{ dokku_skip_key_file }}'
    vtype: 'boolean'
  tags:
  - dokku

- name: debconf dokku/vhost_enable
  debconf:
    name: dokku
    question: 'dokku/vhost_enable'
    value: '{{ dokku_vhost_enable }}'
    vtype: 'boolean'
  tags:
  - dokku

- name: debconf dokku/web_config
  debconf:
    name: dokku
    question: 'dokku/web_config'
    value: '{{ dokku_web_config }}'
    vtype: 'boolean'
  tags:
  - dokku

- name: pin dokku packages
  copy:
    dest: /etc/apt/preferences.d/ansible-hold-{{ item.key }}
    content: |
      Package: {{ item.key }}
      Pin: version {{ item.value }}
      Pin-Priority: 1001
    mode: preserve
  with_dict:
    plugn: "{{ plugn_version }}"
    sshcommand: "{{ sshcommand_version }}"
    herokuish: "{{ herokuish_version }}"
    dokku: "{{ dokku_version }}"
  tags:
  - dokku
  - dokku-install

- name: install dokku packages
  apt:
    name: "{{ item.key }}={{ item.value }}"
  with_dict:
    plugn: "{{ plugn_version }}"
    sshcommand: "{{ sshcommand_version }}"
    herokuish: "{{ herokuish_version }}"
    dokku: "{{ dokku_version }}"
  tags:
  - dokku
  - dokku-install

- name: write vhost
  when: dokku_vhost_enable | bool
  copy:
    content: "{{ dokku_hostname }}"
    dest: /home/dokku/VHOST
    mode: preserve
  tags:
  - dokku
  - dokku-install
