- name: https apt transport for docker repository
  apt:
    name: apt-transport-https
  tags:
    - dokku
    - docker-repo

- name: gnupg-curl for docker gpgkey
  apt:
    name: gnupg-curl
    state: '{{ "present" if ansible_distribution_release in
               [ "wheezy", "jessie", "precise", "trusty", "xenial" ]
               else "absent" }}'
  tags:
    - dokku
    - docker-repo

- name: apt.docker.com key
  apt_key:
    id: "{{ docker_apt_key_sig }}"
    keyserver: "{{ docker_apt_key_url }}"
    state: present
  tags:
    - dokku
    - docker-repo

- name: download.docker.com key
  apt_key:
    id: "{{ docker_download_key_sig }}"
    keyserver: "{{ docker_download_key_url }}"
    state: present
  tags:
    - dokku
    - docker-repo

- name: packagecloud dokku apt key
  apt_key:
    url: https://packagecloud.io/dokku/dokku/gpgkey
  tags:
    - dokku

- name: docker repo
  apt_repository:
    filename: docker
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable'
    state: present
  tags:
    - dokku
    - docker-repo

- name: dokku repo
  apt_repository:
    filename: dokku
    repo: 'deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main'
    state: present
  tags:
    - dokku

- name: debconf dokku/hostname
  debconf:
    name: dokku
    question: 'dokku/hostname'
    value: '{{ dokku_hostname }}'
    vtype: 'string'
  tags:
    - dokku

- name: debconf dokku/key_file
  debconf:
    name: dokku
    question: 'dokku/key_file'
    value: '{{ dokku_key_file }}'
    vtype: 'string'
  tags:
    - dokku

- name: debconf dokku/skip_key_file
  debconf:
    name: dokku
    question: 'dokku/skip_key_file'
    value: '{{ dokku_skip_key_file }}'
    vtype: 'boolean'
  tags:
    - dokku

- name: debconf dokku/vhost_enable
  debconf:
    name: dokku
    question: 'dokku/vhost_enable'
    value: '{{ dokku_vhost_enable }}'
    vtype: 'boolean'
  tags:
    - dokku

- name: debconf dokku/web_config
  debconf:
    name: dokku
    question: 'dokku/web_config'
    value: '{{ dokku_web_config }}'
    vtype: 'boolean'
  tags:
    - dokku

- name: install dokku packages
  apt:
    name: "{{ item.key }}={{ item.value }}"
  with_dict:
    plugn: "{{ plugn_version }}"
    sshcommand: "{{ sshcommand_version }}"
    herokuish: "{{ herokuish_version }}"
    dokku: "{{ dokku_version }}"
  tags:
    - dokku
    - dokku-install

- name: pin dokku packages
  copy:
    dest: /etc/apt/preferences.d/ansible-hold-{{ item.key }}
    content: |
      Package: {{ item.key }}
      Pin: version {{ item.value }}
      Pin-Priority: 1001
  with_dict:
    plugn: "{{ plugn_version }}"
    sshcommand: "{{ sshcommand_version }}"
    herokuish: "{{ herokuish_version }}"
    dokku: "{{ dokku_version }}"
  tags:
    - dokku
    - dokku-install
