- import_tasks: init.yml

- import_tasks: nginx.yml
  tags:
  - dokku
  - dokku-nginx

- import_tasks: install.yml
  tags:
  - dokku
  - dokku-install

- import_tasks: dokku-daemon.yml
  tags:
  - dokku
  - dokku-daemon

- import_tasks: ssh-keys.yml
  when: dokku_users is defined
  tags:
  - dokku
  - dokku-ssh-keys

- name: dokku plugin:list
  command: dokku plugin:list
  changed_when: false
  register: installed_dokku_plugins
  tags:
  - dokku
  - dokku-plugins

- name: install apt packages
  apt:
    name:
    - moreutils    # for plugin updates
    - rsync        # for dokku git:sync
    - cron         # missing on debian11
  tags:
  - dokku-plugins

- name: dokku:plugin install
  command: dokku plugin:install {{ item.url }} --name {{ item.name }}
  tags:
  - dokku
  - dokku-plugins
  when: dokku_plugins is defined and installed_dokku_plugins.stdout.find(item.name) == -1
  changed_when: true
  with_items: "{{ dokku_plugins }}"

- name: dokku plugin:update
  cron:
    name: "dokku plugin:update {{ item.name }}"
    minute: "0"
    hour: "12"
    user: "root"
    job: "/usr/bin/chronic /usr/bin/dokku plugin:update {{ item.name }}"
    cron_file: "dokku-plugin-update-{{ item.name }}"
  when: dokku_plugins is defined and not item.url.endswith(".tar.gz")
  with_items: "{{ dokku_plugins }}"
  tags:
  - dokku
  - dokku-plugins

- name: dokku:plugin install-dependencies  # noqa: no-changed-when
  command: dokku plugin:install-dependencies
  tags:
  - dokku
  - dokku-plugins
  - molecule-idempotence-notest
  when: dokku_plugins is defined
